blueprint:
  name: Smart Thermostat Monitor
  description: >
    Automatically controls thermostat based on outdoor temperature, indoor temperature,
    humidity levels, and presence detection. Uses heat_cool (auto) mode as the default
    for efficient dual-setpoint operation. Respects manual overrides with a 1-hour
    timeout, and applies emergency overrides for extreme temperatures or humidity.
    Applies Auxiliary preset for heating (gas preferred over electric) and Energy Cool
    for cooling.
  domain: automation

  input:
    # ─── Climate Entity ───────────────────────────────────────────────────────
    climate_entity:
      name: Climate Entity
      description: The thermostat to control
      selector:
        entity:
          domain: climate

    # ─── Presence ─────────────────────────────────────────────────────────────
    presence_person_1:
      name: First Person
      description: First person entity for presence detection
      selector:
        entity:
          domain: person

    presence_person_2:
      name: Second Person
      description: Second person entity for presence detection
      selector:
        entity:
          domain: person

    home_zone:
      name: Home Zone
      description: Zone entity representing home
      default: zone.home
      selector:
        entity:
          domain: zone

    # ─── Sensors ──────────────────────────────────────────────────────────────
    outdoor_temp_sensors:
      name: Outdoor Temperature Sensors
      description: One or more outdoor temperature sensors (will be averaged)
      selector:
        entity:
          domain: sensor
          device_class: temperature
          multiple: true

    indoor_temp_sensors:
      name: Indoor Temperature Sensors
      description: One or more indoor temperature sensors (will be averaged)
      selector:
        entity:
          domain: sensor
          device_class: temperature
          multiple: true

    indoor_humidity_sensors:
      name: Indoor Humidity Sensors
      description: One or more indoor humidity sensors (will be averaged)
      selector:
        entity:
          domain: sensor
          device_class: humidity
          multiple: true

    # ─── Outdoor Temperature Thresholds ──────────────────────────────────────
    outdoor_heat_threshold:
      name: Outdoor Heating Threshold
      description: Below this outdoor temperature the system biases toward heating.
      default: 60
      selector:
        number:
          min: 30
          max: 75
          unit_of_measurement: "°F"

    outdoor_cool_threshold:
      name: Outdoor Cooling Threshold
      description: >
        Above this outdoor temperature the system biases toward cooling.
        Between the two thresholds is shoulder season.
      default: 70
      selector:
        number:
          min: 60
          max: 90
          unit_of_measurement: "°F"

    # ─── Indoor Emergency Thresholds ─────────────────────────────────────────
    indoor_too_cold:
      name: Indoor Too Cold Emergency
      description: >
        If indoor temp drops below this, force heat mode regardless of outdoor
        temperature or manual override.
      default: 65
      selector:
        number:
          min: 55
          max: 72
          unit_of_measurement: "°F"

    indoor_too_hot:
      name: Indoor Too Hot Emergency
      description: >
        If indoor temp rises above this, force cool mode regardless of outdoor
        temperature or manual override.
      default: 78
      selector:
        number:
          min: 70
          max: 85
          unit_of_measurement: "°F"

    # ─── Temperature Setpoints (Home) ─────────────────────────────────────────
    heat_setpoint_home:
      name: Heat Setpoint — Home
      description: Lower bound of heat_cool band when someone is home.
      default: 70
      selector:
        number:
          min: 60
          max: 80
          unit_of_measurement: "°F"

    cool_setpoint_home:
      name: Cool Setpoint — Home
      description: Upper bound of heat_cool band when someone is home.
      default: 74
      selector:
        number:
          min: 65
          max: 82
          unit_of_measurement: "°F"

    # ─── Temperature Setpoints (Away) ─────────────────────────────────────────
    heat_setpoint_away:
      name: Heat Setpoint — Away
      description: Lower bound of heat_cool band when nobody is home.
      default: 65
      selector:
        number:
          min: 55
          max: 72
          unit_of_measurement: "°F"

    cool_setpoint_away:
      name: Cool Setpoint — Away
      description: Upper bound of heat_cool band when nobody is home.
      default: 78
      selector:
        number:
          min: 70
          max: 85
          unit_of_measurement: "°F"

    # ─── Humidity Settings ────────────────────────────────────────────────────
    high_humidity_threshold:
      name: High Humidity Threshold
      description: >
        Above this level the system forces cool mode to dehumidify.
        Overrides manual mode.
      default: 60
      selector:
        number:
          min: 40
          max: 80
          unit_of_measurement: "%"

    dehumidify_temp:
      name: Dehumidification Temperature
      description: Target temperature when running in dehumidification mode.
      default: 70
      selector:
        number:
          min: 65
          max: 78
          unit_of_measurement: "°F"

    # ─── Manual Override ──────────────────────────────────────────────────────
    manual_override_boolean:
      name: Manual Override Boolean
      description: Input boolean that tracks whether a manual override is active.
      default: input_boolean.thermostat_manual_mode
      selector:
        entity:
          domain: input_boolean

variables:
  # All threshold comparisons happen here in variables, not in triggers.
  # This avoids the !input-inside-value_template syntax error.

  avg_outdoor_temp: >
    {% set ns = namespace(total=0, count=0) %}
    {% for sensor in outdoor_temp_sensors %}
      {% set val = states(sensor) | float(-999) %}
      {% if val != -999 %}
        {% set ns.total = ns.total + val %}
        {% set ns.count = ns.count + 1 %}
      {% endif %}
    {% endfor %}
    {{ (ns.total / ns.count) | round(1) if ns.count > 0 else 0 }}

  avg_indoor_temp: >
    {% set ns = namespace(total=0, count=0) %}
    {% for sensor in indoor_temp_sensors %}
      {% set val = states(sensor) | float(-999) %}
      {% if val != -999 %}
        {% set ns.total = ns.total + val %}
        {% set ns.count = ns.count + 1 %}
      {% endif %}
    {% endfor %}
    {{ (ns.total / ns.count) | round(1) if ns.count > 0 else 0 }}

  avg_indoor_humidity: >
    {% set ns = namespace(total=0, count=0) %}
    {% for sensor in indoor_humidity_sensors %}
      {% set val = states(sensor) | float(-999) %}
      {% if val != -999 %}
        {% set ns.total = ns.total + val %}
        {% set ns.count = ns.count + 1 %}
      {% endif %}
    {% endfor %}
    {{ (ns.total / ns.count) | round(1) if ns.count > 0 else 0 }}

  anyone_home: >
    {{ is_state(presence_person_1, 'home') or is_state(presence_person_2, 'home') }}

  leaving_home: >
    {% set trigger_entity = trigger.entity_id | default('') %}
    {% if trigger_entity in [presence_person_1, presence_person_2] %}
      {{ trigger.to_state.state != 'home' and
         not (is_state(presence_person_1, 'home') or is_state(presence_person_2, 'home')) }}
    {% else %}
      false
    {% endif %}

  manual_mode_active: >
    {{ is_state(manual_override_boolean, 'on') }}

  # Threshold comparisons use the averaged values computed above.
  # These are safe here because variables are resolved at run time, not parse time.
  outdoor_needs_heat: >
    {{ avg_outdoor_temp | float < outdoor_heat_threshold | float }}

  outdoor_needs_cool: >
    {{ avg_outdoor_temp | float > outdoor_cool_threshold | float }}

  shoulder_season: >
    {{ not outdoor_needs_heat and not outdoor_needs_cool }}

  humidity_emergency: >
    {{ avg_indoor_humidity | float > high_humidity_threshold | float }}

  indoor_too_cold_now: >
    {{ avg_indoor_temp | float < indoor_too_cold | float }}

  indoor_too_hot_now: >
    {{ avg_indoor_temp | float > indoor_too_hot | float }}

  indoor_temp_emergency: >
    {{ indoor_too_cold_now or indoor_too_hot_now }}

trigger:
  # Presence changes — platform: state works correctly with !input entity lists
  - platform: state
    entity_id: !input presence_person_1
    id: presence_change

  - platform: state
    entity_id: !input presence_person_2
    id: presence_change

  # Sensor state changes — fire whenever any sensor updates.
  # Threshold evaluation happens in the action variables block, not here.
  # platform: state works correctly with !input multiple-entity lists.
  - platform: state
    entity_id: !input outdoor_temp_sensors
    id: outdoor_temp_changed

  - platform: state
    entity_id: !input indoor_temp_sensors
    id: indoor_temp_changed

  - platform: state
    entity_id: !input indoor_humidity_sensors
    id: humidity_changed

  # Periodic re-evaluation every 30 minutes regardless of sensor changes.
  # Catches shoulder-season transitions and drift without needing a trigger event.
  - platform: time_pattern
    minutes: "/30"
    id: periodic_check

condition: []

action:
  # ── Step 1: Clear manual override when last person leaves ─────────────────────
  - if:
      - condition: template
        value_template: "{{ leaving_home }}"
    then:
      - service: input_boolean.turn_off
        target:
          entity_id: !input manual_override_boolean
      - service: system_log.write
        data:
          message: "Smart Thermostat: Last person left — clearing manual override."
          level: info

  # ── Step 2: Gate — act on emergencies always, otherwise skip if manual mode ───
  - if:
      - condition: template
        value_template: >
          {{ humidity_emergency or indoor_temp_emergency or leaving_home or not manual_mode_active }}
    then:
      # ── Step 3: Resolve target mode and setpoints ───────────────────────────
      - variables:
          target_mode: >
            {% if humidity_emergency %}
              cool
            {% elif indoor_too_cold_now %}
              heat
            {% elif indoor_too_hot_now %}
              cool
            {% elif not anyone_home and shoulder_season %}
              off
            {% else %}
              heat_cool
            {% endif %}

          effective_low: >
            {% if anyone_home %}
              {{ heat_setpoint_home | float }}
            {% else %}
              {{ heat_setpoint_away | float }}
            {% endif %}

          effective_high: >
            {% if anyone_home %}
              {{ cool_setpoint_home | float }}
            {% else %}
              {{ cool_setpoint_away | float }}
            {% endif %}

          effective_single_temp: >
            {% if humidity_emergency %}
              {{ dehumidify_temp | float }}
            {% elif indoor_too_cold_now %}
              {% if anyone_home %}
                {{ heat_setpoint_home | float }}
              {% else %}
                {{ heat_setpoint_away | float }}
              {% endif %}
            {% else %}
              {% if anyone_home %}
                {{ cool_setpoint_home | float }}
              {% else %}
                {{ cool_setpoint_away | float }}
              {% endif %}
            {% endif %}

      # ── Step 4: Log decision ────────────────────────────────────────────────
      - service: system_log.write
        data:
          message: >
            Smart Thermostat [{{ trigger.id | default('unknown') }}]:
            mode={{ target_mode }},
            {% if target_mode == 'heat_cool' %}band={{ effective_low }}–{{ effective_high }}°F,
            {% elif target_mode == 'off' %}off (shoulder season, nobody home),
            {% else %}target={{ effective_single_temp }}°F,
            {% endif %}
            outdoor={{ avg_outdoor_temp }}°F, indoor={{ avg_indoor_temp }}°F,
            humidity={{ avg_indoor_humidity }}%, home={{ anyone_home }},
            hum_emergency={{ humidity_emergency }}, temp_emergency={{ indoor_temp_emergency }}
          level: info

      # ── Step 5: Call the control script ────────────────────────────────────
      - service: script.smart_thermostat_control
        data:
          mode: "{{ target_mode }}"
          target_temp: "{{ effective_single_temp }}"
          target_temp_low: "{{ effective_low }}"
          target_temp_high: "{{ effective_high }}"
          humidity_override: "{{ humidity_emergency }}"
          dehumidify_temp: !input dehumidify_temp
          set_energy_preset: true

    else:
      - service: system_log.write
        data:
          message: >
            Smart Thermostat [{{ trigger.id | default('unknown') }}]:
            manual override active — skipping.
            (outdoor={{ avg_outdoor_temp }}°F, indoor={{ avg_indoor_temp }}°F)
          level: info

mode: single
max_exceeded: silent
